name: Tests

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16, 18]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:cov

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
        if: matrix.node == 12 && startsWith(matrix.os, 'ubuntu')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
